
// Auto-generated by AutoPilot on 28-07-2023 at 23:27:28

const express = require('express');
const router = express.Router();

//Route to generate cube of a number
router.get('/testing', (req, res) => {
    // Get the number from the query parameter
    const number = req.query.number;
    try {
        // Generate cube of the number
        const answer = Math.pow(number, 3);
        // Return response
        res.status(200).json({ result: answer });
    } catch (err) {
        // Return error response
        res.status(500).json({ error: 'Encountered an error' });
    }
});

module.exports = router;